---
#
# Configuring Zimbra OSE
################################################################################
- name: Setting up syslog configuration for Zimbra
  command: ./zmsyslogsetup
  args:
    chdir: /opt/zimbra/libexec/

- name: Starting automatic scanning of Email using ClamAV
  command: ./zmprov mcf zimbraAttachmentsScanURL  clam://localhost:3310/
  args:
    chdir: /opt/zimbra/bin/

- name: Enabling automatic scanning of Email using ClamAV
  command: ./zmprov mcf zimbraAttachmentsScanEnabled TRUE 
  args:
    chdir: /opt/zimbra/bin/

